apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    signingConfigs {
        if (keystorePropertiesFile.exists()) {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }
    buildFeatures.viewBinding = true
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // Автоматический инкремент номера сборки
    def versionPropsFile = file('version.properties')
    if (versionPropsFile.canRead()) {
        def versionProps = new Properties()
        versionProps.load(new FileInputStream(versionPropsFile))
        def name = versionProps['VERSION_NAME']
        def code = versionProps['VERSION_CODE'].toInteger() + 1
        versionProps['VERSION_CODE'] = code.toString()
        versionProps.store(versionPropsFile.newWriter(), null)

        defaultConfig {
            applicationId "com.asinosoft.cdm"
            minSdkVersion 24
            compileSdk = 37
            targetSdkVersion 37
            versionCode code
            versionName "${name}.${code}"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }
    } else {
        throw new GradleException("Could not read version.properties!")
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            debuggable true
            minifyEnabled false
            pseudoLocalesEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "Manager@${variant.name}_${variant.versionName}.apk"
                }
            }
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    namespace 'com.asinosoft.cdm'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.appcompat
    implementation libs.core.ktx
    implementation libs.core.splashscreen
    implementation libs.constraintlayout
    implementation libs.fragment.ktx
    implementation libs.legacy.support.v4
    implementation libs.recyclerview
    implementation libs.lifecycle.extensions1
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.preference.ktx
    implementation libs.viewpager2
    implementation libs.webkit
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx
    implementation libs.play.services.ads
    testImplementation libs.junit
    testImplementation libs.mockito.core
    androidTestImplementation libs.runner
    implementation libs.circleimageview
    implementation libs.gson
    implementation libs.swipelayout
    implementation libs.library
    implementation libs.utils.v4
    implementation libs.timber

    // Firebase
    implementation libs.firebase.bom
    implementation libs.firebase.config.ktx
    implementation libs.firebase.analytics.ktx

    //Optional: see how to use the utility.
    implementation libs.bubbleseekbar
    implementation libs.colorpicker

    implementation libs.ripplebackground.library

    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    implementation libs.libphonenumber

    //dialer
    implementation libs.material

    //Yandex Mobile Ads
    implementation libs.mobileads

    // Runtime log-reader
//    debugImplementation 'com.willowtreeapps.hyperion:hyperion-core:0.9.27'
//    debugImplementation 'com.willowtreeapps.hyperion:hyperion-timber:0.9.27'
}

kotlin {
    jvmToolchain(17)
}